config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase } # "before_save { email.downcase! } will do the same thing"
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50}
#  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      #redirect_to user #alterado para a linha abaixo listing 9.19
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  before_action :signed_out_user, only: [:create, :new]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    if !user.admin?
      User.find(params[:id]).destroy
      flash[:success] = "User deleted."
    else
      flash[:error] = "Admin users cannot be deleted"
    end
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters
    
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in." unless signed_in?
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user? (@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def signed_out_user
      unless signed_out?
        flash[:error] = 'To create a new user, you first need to logout'
        redirect_to(root_url) 
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Camnopous"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_out?
    current_user.nil?
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <a href="http://www.camnopous.com/">Camnopous</a>
    
  <nav>
    <ul>
      <li><%= link_to "About",    about_path  %></li>
      <li><%= link_to "Contact",  contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "camnopous", root_path, id: "logo" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav pull-right navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
        </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag :modernizr %>                                     
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <!-- <%= debug(params) if Rails.env.development? %> -->
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  We are a new company looking to puting all of your house on the cloud!!! The Camnopous is just the first product that you loves to use in this new era!!!
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact us to get if you wanna more information via email:  information@camnopous.com
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help with one of the following:

</p>

app/views/static_pages/home.html.erb
<div class="container">

  <div class="center hero-unit">
    <h1>Camnopous, the easiest cloud camera</H1>
  
    <h2>
      Register to have a little taste of the first product that will revolutionize your house life!!!
    </h2>
  
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"  %>
  </div>


  <!-- Example row of columns -->
  <div class="row" style="margin-top:50px;">
    <div class="col-md-3 col-sm-3"></div>
    <div class="col-md-2 col-sm-2 col-xs-4 ext-box">
      <div class="video-box">
        <%= link_to image_tag("get_image1.jpg", alt: "puppets", class: "img-responsive"), 'https://blank' %> 
        <br>video1
      </div>
		</div>
    <div class="col-md-2 col-sm-2 col-xs-4 ext-box">
      <div class="video-box">
        <%= link_to image_tag("get_image2.jpg", alt: "3D printers", class: "img-responsive"), 'https://blank' %> 
        <br>video2
      </div>
		</div>
    <div class="col-md-2 col-sm-2 col-xs-4 ext-box">
      <div class="video-box">
        <%= link_to image_tag("get_image3.jpg", alt: "Security cam", class: "img-responsive"), 'https://blank' %> 
        <br>video3
      </div>
		</div>
    <div class="col-md-3 col-sm-3"></div>
	</div> <!-- row 1 -->
 

</div> <!--end container-->

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>

<%= f.label :name, 'Your Name' %>
<%= f.text_field :name, class: "form-control", placeholder: "Name" %>

<%= f.label :email %>
<%= f.email_field :email, class: "form-control", placeholder: "Email" %>

<%= f.label :password %>
<%= f.password_field :password, class: "form-control", placeholder: "Password"  %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation"  %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-5 col-xs-12 col-centered">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>

      <div class="col-md-6 col-xs-10 col-centered">
        <%= f.submit "Save changes", class: "btn btn-primary" %>
      </div>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank", >change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-5 col-xs-12 col-centered">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <div class="col-md-6 col-xs-10 col-centered">
        <%= f.submit "Create my account", class: "btn btn-lg btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class= "row" >
  <aside class="span4">
    <section>
      <h1>
      <%= gravatar_for @user %>  
      <%= @user.name %>
      </h1>
    </section>
    </aside>
</div>